name: Storing Azure DC IP ranges

on:
  push:
    paths:
    - '.github/workflows/*'
  schedule:
    - cron: '0 3 */7 * *'

jobs:
  get-and-store-az-ip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  

    - name: Store accounts certificate
      run: echo ${{ secrets.SPN_KEY_BASE64 }} | base64 --decode > /tmp/cert.pem ; ls -la

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.SPN_ID }} -p /tmp/cert.pem --tenant ${{ secrets.TENANT_ID }} -o none

    - name: Storing ip ranges
      run: cd ip; ./script.sh

    - name: Publishing the changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git add .
        git commit -m $(date +%F)
        git push
