name: Storing Azure DC IP ranges

on:
  push:
    paths:
    - '.github/workflows/*'
  schedule:
    - cron: '0 0 1 * *'



jobs:
  get-and-store-az-ip:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  
        
    - run: |
        date > published.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Published Changes"
        git push

    - name: Store account certificate
      run: echo ${{ secrets.SPN_KEY_BASE64 }} | base64 --decode > cert.pem ; ls -la
      working-directory: /tmp

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.SPN_ID }} -p cert.pem --tenant ${{ secrets.TENANT_ID }} -o none
      working-directory: /tmp
